### ISSUE TITLE
jq command loses data

### ISSUE THREAD

**Issue by underdog** [msencer/remarkable_templates#10]
Just letting you know, I have used the jq command in your script and I end up losing templates in the redirected output file.  I'm not familiar with jq a lot, so I haven't looked into it much, but I'm sure there's an answer.

So, when I do a wordcount on the named objects for each file, i get these results. the merged file is the redirected output of the jq command.  I'd expect to see 81 files, not 61 

grep \"name templates.original.json | wc -l
79
grep \"name templates.additional.json | wc -l
9
grep \"name templates.merged.json | wc -l
61

**Comment by underdog** [comment]
I figured out what is going on.  the jq command is using the .name to filter on the elements, well, there are LandScape, LS, and Portrait, P, elements.  So, it is losing either the LS or P of duplicate named elements.

**Comment by underdog** [comment]
the jq command needs to append the new templates within the existing original json templates.

**Comment by underdog** [comment]
so, if you run the command and filter on .filename, you still lose one, Blank, because it is the same filename, unlike the others which are unique
Also, running it with --ascii-output guarantees that there is no unicode symbols output.  This really helps if you have to edit the file via vim or such.  I've tried setting encoding and fileencoding and vim still wouldn't show the unicode in the redirected output file.  using --ascii-output guarantees the output is human readable

jq --ascii-output -n '{ templates: [ inputs.templates ] | add | unique_by(.filename)}'

**Comment by msencer** [comment]
Thanks for reporting this problem! I solved it by filtering with multiple keys. Result:
```
grep "name" templates.json | wc -l
     158
grep "name" templates.addition.json | wc -l
     12
grep "name" templates.merged.json | wc -l
     170
```
