### ISSUE TITLE
reMarkable too slow after installing

### ISSUE THREAD

**Issue by vedgar** [msencer/remarkable_templates#2]
Installation worked without problems (though thumbnails for new templates are out of sync), but since then, my reMarkable device started acting extremely slowly (about a minute) when opening some documents (always the same documents, about 20 pages). Restarting reMarkable didn't help. Do you have any idea what might be the issue? And can the new templates be uninstalled?

**Comment by msencer** [comment]
Hey @vedgar,

TBH, I have no idea what would cause such a problem, I haven't experienced anything like that on my own device.

For uninstalling the templates, you can SSH into your device, edit the ```/usr/share/remarkable/templates/templates.json``` file and remove the JSON objects related to the custom templates. Then you should run ```systemctl restart xochitl``` command or restart the device to apply the changes. You can also delete the PNG files from ```/usr/share/remarkable/templates``` folder.

I hope this will solve your problem.

**Comment by vedgar** [comment]
Thanks. In the meantime a new update to reMarkable software was released, which solved both problems ("uninstalling" custom templates, and slowness of the device), so I still don't know whether there is a link. But I'll keep in mind your instructions for uninstalling (you might want to add them to the readme).
