### ISSUE TITLE
Install script connects as current host user instead of 'root@rem'

### ISSUE THREAD

**Issue by gjvanouwendorp** [msencer/remarkable_templates#3]
Title says about everything. The 'ssh' lines in the install script omit the username to connect as, which should be 'root'. By omitting the username, ssh tries to connect as the current user at the host machine, which results in an error.
I will add a pull request with the updated and tested install script.

**Comment by msencer** [comment]
Hey @gjvanouwendorp, I set the user in the .ssh/config file(see the example below)
```
Host rem
  HostName [ip_placeholder]
  AddKeysToAgent yes
  UseKeychain yes
  IdentityFile [file_path_placeholder]
  User root
```
do you think that's better to have it explicitly in the script?
